feat: [CO-719] Update ClamScanner class to work with Carbonio ClamAV service
Zextras/carbonio-clam-scanner-store pull request #4
Opened 2023-06-09 08:14 UTC by keshavbhatt

**What has changed:**
- ClamScanner now uses new ClamAVClient which supports clamd INSTREAM command for scanning files
- Config provide fallback setting and uses them to communicate with Carbonio ClamAV service if supplied one are invalid
- Code cleanup

**TODO:** 
- [ ] Align log4j dependency with the one provided by main runtime once corresponding PRs are merged.

2023-06-09 09:40 UTC, frisonisland commented on src/java-test/com/zimbra/clam/ClamScannerTest.java
> +  public void testSetURLValidURL() {
Mmmh probably this test should be named InvalidUrl if we test it is invalid

2023-06-09 10:02 UTC, keshavbhatt commented on src/java-test/com/zimbra/clam/ClamScannerTest.java
> +  public void testSetURLValidURL() {
Nah, we are testing valid URL, by invoking ClamScanner.setUrl, passing a valid url to it. Test fails if any exception occur.

2023-06-09 10:08 UTC, frisonisland commented on src/java/com/zimbra/clam/ClamScanner.java
> +  private void createDefaultClamAVClient() {
This looks like a factory method and that can be static

2023-06-09 10:13 UTC, frisonisland commented on src/java/com/zimbra/clam/ClamScanner.java
> +  private void createClamAVClient(String hostname, int port) {
Same for this, could be a factory static pattern (creational). I see the client is a private variable of ClamScanner. If possible the scanner should be created as `ClamScanner(ClamAVClient client)`.
(Btw I'm just making suggestions for improvement, I understand it is not this way bc of old codebase)

2023-06-09 10:16 UTC, frisonisland commented on src/java/com/zimbra/clam/ClamScannerExt.java
> +        ClamScanner clamScanner = new ClamScanner();
We can pass the client in here.
However, if the client is expected to change based on localconfig (e.g.: url, options, etc.), we can pass a Factory class instead, so to load localconfig at runtime. The factory then could return the client with factory.createClient().

2023-06-09 10:17 UTC, frisonisland requested changes
I left some comments about one test and code structure. Consider passing the client in constructor to scanner!

2023-06-09 10:19 UTC, frisonisland commented on src/java-test/com/zimbra/clam/ClamScannerTest.java
> +  public void testSetURLValidURL() {
Oh ok, I understand now!

2023-06-09 10:42 UTC, keshavbhatt commented on src/java/com/zimbra/clam/ClamScannerExt.java
> +        ClamScanner clamScanner = new ClamScanner();
I agree with all your points but, the extention class is loaded once when mailbox starts. Reads config duing its initialization. So, expect only once instance of ClamScanner, with whatever config it loaded during startup. With all this, its efficient to create only once instance of ClamAVClient too.

2023-06-09 13:46 UTC, keshavbhatt commented on src/java/com/zimbra/clam/ClamScannerExt.java
> +        ClamScanner clamScanner = new ClamScanner();
> Also I see a new instance of CLamScanner is created for each url actually

There can be multiple url (useful if admin have multiple clamav instances with different capabilities), representing multiple scanners. These scanners are registered in the UplaodScanner class inside mailbox.

Overall, if you will revisit the classes you will understand why the design is like this. We also have to take care of proper client initialization which is used by UploadScanner to figure out if the scanner is able to perform scans. I will not put much efforts as i am satisfied with current design, the code is mostly testable.

> Also method setUrl(String utl) violates the logic of setters

setUrl is our implementation, I know url is not required but this is a constrain we have to work with. ClamAVClient just need hostname and port to open socket connection. We need to take care of correclty parsing the URL to host and port to properly initialize client and Scanner in total.

2023-06-09 14:25 UTC, frisonisland commented on src/java/com/zimbra/clam/ClamScannerExt.java
> +        ClamScanner clamScanner = new ClamScanner();
Also, aside the big logic, it's the method name I have issue with, it should be called setClient(String url), not setUrl. So it would be either move the logic elsewhere and just set the url, or rename the method, to keep it clean.

2023-06-09 14:44 UTC, keshavbhatt commented on src/java/com/zimbra/clam/ClamScannerExt.java
> +        ClamScanner clamScanner = new ClamScanner();
>  aside the big logic, it's the method name I have issue with, it should be called setClient(String url), not setUrl
Yes, its coming from the abstract class that we are extending. If we have these methods layed like this, question is setUrl to what? I mean its a void method and a constrain.

> not to make things just "work", but also lay the code down in a simple-modular
I agree, we try do focus on that most of the time. I hope you were able to find little modularity in the new version :D (The client logic was inside the scanner in the past). Now its separate. 

> easy to understand it and maintainable, so even a "novice" could work on it
There is nothing tricky or hard to understand going on here. The ClamScanner has one dependency called ClamAVClient, we initialize it inside scanner since it extend the API hook, You cannot do it outside given the contains we have right now. If we want to modify the UploadScanner class then the design changes are possible.

I avoided creating unnecessary Factory classes (I could have created ClamAVClientFatory, SocketFactory etc) since there is no use of em, you will just call it once while keeping that extra unnecessary logic all over these classes.

2023-06-14 08:06 UTC, Polpetta requested changes
On top of the notes I've left you, please also mark all the variables as final unless they have to be mutable. Do not put final variables inside try-with-resources as it will break input/output streams

2023-06-14 09:44 UTC, keshavbhatt commented on src/java/com/zimbra/clam/ClamScanner.java
> +      return ERROR;
I opted for a simpler solution for several reasons. Thanks :)

2023-06-14 09:44 UTC, keshavbhatt commented on src/java-test/com/zimbra/clam/ClamAVClientTest.java
> +    Assert.assertTrue(result);
done.

2023-06-14 09:49 UTC, Polpetta commented on src/java/com/zimbra/clam/ClamScanner.java
> +      return ERROR;
As long as it is sound and is maintainable its ok :+1:

2023-06-16 07:46 UTC, Polpetta approved these changes

2023-06-16 07:46 UTC, Polpetta commented
@keshavbhatt if you want mark all conversations as resolved if you want :+1:

2023-06-16 10:01 UTC, frisonisland commented
@keshavbhatt about log4j no need to wait, there is still a lot of work to do

2023-06-20 14:46 UTC, merged